---
- name : mkdir bootstrap dir
  with_items:
    - '{{dcos_bootstrap_dir}}'
    - '{{dcos_bootstrap_dir}}/genconf'
  file: >-
    path={{item}}
    state=directory
    mode=0755

- name: install ssh key
  copy: >-
    src={{dcos_bootstrap_ssh_key}}
    dest={{dcos_bootstrap_dir}}/genconf/ssh_key
    mode=0600
    
- name: write templates...
  with_items:
    - genconf/ip-detect
    - genconf/config.yaml
  register: dcos_bootstrap_config
  template: >-
    src={{item}}.j2
    dest={{dcos_bootstrap_dir}}/{{item}}
    mode=0755
    
- name: get installer
  get_url: >-
    url={{dcos_bootstrap_generate_config_url}}
    dest={{dcos_bootstrap_dir}}/{{dcos_bootstrap_generate_config}}
    timeout={{dcos_bootstrap_timeout_seconds}}
    mode=0755
    
- name: generate configuration
  when: dcos_bootstrap_config.changed
  with_items:
    - '{{dcos_bootstrap_dir}}/{{dcos_bootstrap_generate_config}}'
  command: '{{item}}'
  args:
    chdir: '{{dcos_bootstrap_dir}}'

- name: launch bootstrap container
  docker:
    name: dcos-bootstrap
    image: nginx
    state: started
    ports:
      - "{{dcos_bootstrap_port}}:80"
    volumes:
      - "{{dcos_bootstrap_dir}}/genconf/serve:/usr/share/nginx/html:ro"

